import Head from "next/head";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
     const response = await fetch("https://jsonplaceholder.typicode.com/users");
     const users = await response.json();
     return {
          props: {
               users,
          },
     };
}

export default function Home({ users }) {
     return (
          <div className={styles.container}>
               <Head>
                    <title>User List</title>
                    <meta name="description" content="Generated by create-next-app" />
                    <link rel="icon" href="/favicon.ico" />
               </Head>

               <main className={styles.main}>
                    <h1 className="text-3xl font-bold mb-4">Users</h1>
                    <ul className="list-disc space-y-2">
                         {users.map((user) => (
                              <li key={user.id} className="flex space-x-2">
                                   <span className="font-medium">{user.name}</span>
                                   <span className="text-gray-500">({user.username})</span>
                              </li>
                         ))}
                    </ul>
               </main>
          </div>
     );
}


